import type { MaterialConstraintState, RemodelKnowledgeEntry } from './types'

export const DEFAULT_MATERIAL_CONSTRAINTS: MaterialConstraintState = {
  acceptBlueprintCost: false,
  acceptCatapultCost: false,
  acceptActionReportCost: false,
  acceptOtherRareMaterials: false,
}

export const REMODEL_KNOWLEDGE_BASE: RemodelKnowledgeEntry[] = [
  {
    id: 'abukuma-kai-ni',
    currentAliases: ['阿武隈', '阿武隈改'],
    targetName: '阿武隈改二',
    targetLevel: 75,
    rareMaterials: ['blueprint'],
    capabilityTags: ['opening_torpedo'],
    utilityTags: ['transport', 'quest'],
    payoffClass: 'high',
    curatedPriority: 98,
    primaryReason: '阿武隈改二能提供開幕雷擊與穩定的運輸編成價值。',
  },
  {
    id: 'ise-kai-ni',
    currentAliases: ['伊勢', '伊勢改'],
    targetName: '伊勢改二',
    targetLevel: 88,
    rareMaterials: ['blueprint', 'catapult'],
    capabilityTags: ['aviation_battleship'],
    utilityTags: ['quest', 'fleet_flexibility'],
    payoffClass: 'high',
    curatedPriority: 97,
    primaryReason: '伊勢改二把戰艦與航空支援整合在同一艘船上，系統價值很高。',
  },
  {
    id: 'hyuuga-kai-ni',
    currentAliases: ['日向', '日向改'],
    targetName: '日向改二',
    targetLevel: 90,
    rareMaterials: ['blueprint', 'catapult'],
    capabilityTags: ['aviation_battleship'],
    utilityTags: ['quest', 'fleet_flexibility'],
    payoffClass: 'high',
    curatedPriority: 97,
    primaryReason: '日向改二提供高價值的航空戰艦彈性，對多種編成都實用。',
  },
  {
    id: 'akizuki-kai-ni',
    currentAliases: ['秋月', '秋月改'],
    targetName: '秋月改二',
    targetLevel: 77,
    rareMaterials: [],
    capabilityTags: ['aaci'],
    utilityTags: ['fleet_anti_air'],
    payoffClass: 'high',
    curatedPriority: 96,
    primaryReason: '秋月改二是高品質對空 cut-in 與艦隊防空位的穩定核心。',
  },
  {
    id: 'kaga-kai-ni',
    currentAliases: ['加賀', '加賀改'],
    targetName: '加賀改二',
    targetLevel: 84,
    rareMaterials: ['catapult'],
    capabilityTags: ['carrier_conversion'],
    utilityTags: ['fleet_flexibility', 'quest'],
    payoffClass: 'high',
    curatedPriority: 95,
    primaryReason: '加賀改二能把主力空母位的彈性與後續編成空間一起拉高。',
  },
  {
    id: 'isuzu-kai-ni',
    currentAliases: ['五十鈴', '五十鈴改'],
    targetName: '五十鈴改二',
    targetLevel: 50,
    rareMaterials: [],
    capabilityTags: ['aaci', 'oasw'],
    utilityTags: ['fleet_anti_air', 'fleet_anti_submarine'],
    payoffClass: 'high',
    curatedPriority: 94,
    primaryReason: '五十鈴改二成本低又能補對空與對潛，是很典型的便宜短期勝利。',
  },
  {
    id: 'ooshio-kai-ni',
    currentAliases: ['大潮', '大潮改'],
    targetName: '大潮改二',
    targetLevel: 65,
    rareMaterials: [],
    capabilityTags: ['landing_craft', 'oasw'],
    utilityTags: ['transport', 'fleet_anti_submarine'],
    payoffClass: 'high',
    curatedPriority: 93,
    primaryReason: '大潮改二同時補上大發系與對潛價值，對日常出擊很實用。',
  },
  {
    id: 'mogami-kai-ni',
    currentAliases: ['最上', '最上改'],
    targetName: '最上改二',
    targetLevel: 80,
    rareMaterials: [],
    capabilityTags: ['ship_type_conversion'],
    utilityTags: ['fleet_flexibility', 'transport'],
    payoffClass: 'high',
    curatedPriority: 92,
    primaryReason: '最上改二帶來高泛用性的艦種轉換與後續擴充空間。',
  },
  {
    id: 'kinu-kai-ni',
    currentAliases: ['鬼怒', '鬼怒改'],
    targetName: '鬼怒改二',
    targetLevel: 75,
    rareMaterials: [],
    capabilityTags: ['landing_craft'],
    utilityTags: ['transport', 'expedition'],
    payoffClass: 'high',
    curatedPriority: 91,
    primaryReason: '鬼怒改二把遠征與輸送編成的系統 utility 一次補齊。',
  },
  {
    id: 'fubuki-kai-ni',
    currentAliases: ['吹雪', '吹雪改'],
    targetName: '吹雪改二',
    targetLevel: 70,
    rareMaterials: [],
    capabilityTags: ['aaci'],
    utilityTags: ['fleet_anti_air', 'quest'],
    payoffClass: 'high',
    curatedPriority: 90,
    primaryReason: '吹雪改二是早期就值得投資的萬用防空驅逐。',
  },
  {
    id: 'suzuya-carrier',
    currentAliases: ['鈴谷改二'],
    targetName: '鈴谷航改二',
    targetLevel: 88,
    rareMaterials: ['catapult'],
    capabilityTags: ['carrier_conversion'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'high',
    curatedPriority: 89,
    primaryReason: '鈴谷航改二能把高等級巡洋艦直接轉成很靈活的中型空母位。',
  },
  {
    id: 'kumano-carrier',
    currentAliases: ['熊野改二'],
    targetName: '熊野航改二',
    targetLevel: 88,
    rareMaterials: ['catapult'],
    capabilityTags: ['carrier_conversion'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'high',
    curatedPriority: 89,
    primaryReason: '熊野航改二提供高靈活度的中型空母轉換，對編成調整很有用。',
  },
  {
    id: 'taigei-to-ryuuhou',
    currentAliases: ['大鯨'],
    targetName: '龍鳳',
    targetLevel: 25,
    rareMaterials: [],
    capabilityTags: ['carrier_conversion'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'high',
    curatedPriority: 88,
    primaryReason: '大鯨轉龍鳳是很便宜的艦種轉換，能快速補上空母彈性。',
  },
  {
    id: 'satsuki-kai-ni',
    currentAliases: ['皐月', '皐月改'],
    targetName: '皐月改二',
    targetLevel: 75,
    rareMaterials: [],
    capabilityTags: ['landing_craft'],
    utilityTags: ['expedition', 'transport'],
    payoffClass: 'medium',
    curatedPriority: 86,
    primaryReason: '皐月改二的遠征與大發 utility 很適合長期帳號經營。',
  },
  {
    id: 'fumizuki-kai-ni',
    currentAliases: ['文月', '文月改'],
    targetName: '文月改二',
    targetLevel: 77,
    rareMaterials: [],
    capabilityTags: ['landing_craft'],
    utilityTags: ['expedition', 'transport'],
    payoffClass: 'medium',
    curatedPriority: 85,
    primaryReason: '文月改二偏系統 utility，但長期遠征與輸送價值穩定。',
  },
  {
    id: 'shinshuu-maru-kai',
    currentAliases: ['神州丸'],
    targetName: '神州丸改',
    targetLevel: 40,
    rareMaterials: [],
    capabilityTags: ['landing_craft'],
    utilityTags: ['transport', 'fleet_flexibility'],
    payoffClass: 'medium',
    curatedPriority: 84,
    primaryReason: '神州丸改能更早投入對地與輸送方向的編成用途。',
  },
  {
    id: 'tenryuu-kai-ni',
    currentAliases: ['天龍', '天龍改'],
    targetName: '天龍改二',
    targetLevel: 78,
    rareMaterials: [],
    capabilityTags: ['landing_craft'],
    utilityTags: ['transport'],
    payoffClass: 'medium',
    curatedPriority: 82,
    primaryReason: '天龍改二補上輕巡在輸送與小規模對地方向的實用位。',
  },
  {
    id: 'mutsuki-kai-ni',
    currentAliases: ['睦月', '睦月改'],
    targetName: '睦月改二',
    targetLevel: 65,
    rareMaterials: [],
    capabilityTags: ['landing_craft'],
    utilityTags: ['expedition'],
    payoffClass: 'medium',
    curatedPriority: 80,
    primaryReason: '睦月改二是偏便宜的系統 utility 投資，適合補遠征位。',
  },
  {
    id: 'haruna-kai-ni-otsu',
    currentAliases: ['榛名改二'],
    targetName: '榛名改二乙',
    targetLevel: 88,
    rareMaterials: ['action_report', 'other_rare'],
    otherRareMaterialLabels: ['新型兵装資材'],
    capabilityTags: ['combat_power'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'medium',
    curatedPriority: 76,
    primaryReason: '榛名改二乙屬於高等級後續投資，偏向提升高速戰艦彈性。',
  },
  {
    id: 'chitose-carrier',
    currentAliases: ['千歳', '千歳改', '千歳甲'],
    targetName: '千歳航',
    targetLevel: 35,
    rareMaterials: [],
    capabilityTags: ['carrier_conversion'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'medium',
    curatedPriority: 75,
    primaryReason: '千歳轉成航型是很便宜的空母位擴充。',
  },
  {
    id: 'chiyoda-carrier',
    currentAliases: ['千代田', '千代田改', '千代田甲'],
    targetName: '千代田航',
    targetLevel: 35,
    rareMaterials: [],
    capabilityTags: ['carrier_conversion'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'medium',
    curatedPriority: 75,
    primaryReason: '千代田航能用很低成本換到穩定的輕空母編成彈性。',
  },
  {
    id: 'kirishima-kai-ni-c',
    currentAliases: ['霧島改二'],
    targetName: '霧島改二丙',
    targetLevel: 90,
    rareMaterials: ['action_report', 'other_rare'],
    otherRareMaterialLabels: ['新型兵装資材'],
    capabilityTags: ['combat_power'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'medium',
    curatedPriority: 74,
    primaryReason: '霧島改二丙是偏後段的戰力投資，價值在高速戰艦位的擴充。',
  },
  {
    id: 'kongou-kai-ni-c',
    currentAliases: ['金剛改二'],
    targetName: '金剛改二丙',
    targetLevel: 92,
    rareMaterials: ['action_report', 'other_rare'],
    otherRareMaterialLabels: ['新型兵装資材'],
    capabilityTags: ['combat_power'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'medium',
    curatedPriority: 73,
    primaryReason: '金剛改二丙屬於成熟帳號的強化項目，重點在艦隊彈性而非便宜升級。',
  },
  {
    id: 'hiei-kai-ni-c',
    currentAliases: ['比叡改二'],
    targetName: '比叡改二丙',
    targetLevel: 90,
    rareMaterials: ['action_report', 'other_rare'],
    otherRareMaterialLabels: ['新型兵装資材'],
    capabilityTags: ['combat_power'],
    utilityTags: ['fleet_flexibility'],
    payoffClass: 'medium',
    curatedPriority: 72,
    primaryReason: '比叡改二丙是高等級後續投資，主要補的是高速戰艦位的選項。',
  },
  {
    id: 'ayanami-kai-ni',
    currentAliases: ['綾波', '綾波改'],
    targetName: '綾波改二',
    targetLevel: 70,
    rareMaterials: [],
    capabilityTags: ['combat_power'],
    utilityTags: ['quest'],
    payoffClass: 'medium',
    curatedPriority: 71,
    primaryReason: '綾波改二是高火力泛用驅逐，適合當長期戰力投資。',
  },
]
